### ISSUE TITLE
Type error thrown when schema uses oneOf

### ISSUE THREAD

**Issue by maxmurmann** [sphinx-contrib/openapi#112]
```
schema:

    oneOf:  

         - type: array  

         - type: string 
```

Will throw

`Exception occurred:
  File "/Users/maxmurmann/opt/anaconda3/envs/bullhorn-apis/lib/python3.8/site-packages/sphinxcontrib/openapi/openapi30.py", line 282, in _httpresource
    type=param['schema']['type'],
KeyError: 'type'
` 

whereas I believe this should be a fine formatting for OpenAPI?
