### ISSUE TITLE
Array of string or integer doesn't show its description

### ISSUE THREAD

**Issue by soyangel** [sphinx-contrib/openapi#93]
Hi,

When having  a property like this:

```
      permissions:
        description: Actuators allowed
        example:
        - a0
        - a1
        items:
          type: string
        type: array
```

I get an output where description is not shown:
```
result.acl[].permissions[] (string) –
```

In cases like this (or array of integers maybe) it would be nice to show the description.
